"""
Per-asset prompt library for Realm.
Each entry is the descriptive part added to STYLE_BASE.
"""

BUILDING_PROMPTS: dict[str, str] = {
    "strip_mine": "open-pit mine with ore carts and wooden scaffolding, rocky excavation",
    "foundry": "iron foundry with brick smokestack, molten metal glow, anvil and bellows",
    "timber_yard": "lumber yard with stacked logs, sawmill wheel, wood shavings",
    "grain_row": "wheat field row with golden stalks, sheaves of grain",
    "gristmill": "stone watermill with turning wheel, grain sacks",
    "kiln_shed": "brick kiln shed with orange fire glow, clay pots",
    "wood_shop": "carpenter workshop with plane, saw, wood planks",
    "blast_furnace": "tall blast furnace with molten metal pour, smoke and fire",
    "chemical_works": "alchemical laboratory with glass retorts, colorful vapors",
    "forge_press": "blacksmith forge with press mechanism, glowing hot metal",
    "tool_workshop": "tool workshop with organized tools hanging on wall",
    "machine_shop": "mechanical workshop with gears and precision instruments",
    "assay_lab": "mineral assay laboratory with test tubes and scales",
    "laboratory": "scientific laboratory with chemistry apparatus, periodic table",
    "power_shed": "electricity generator shed with coils and lightning bolt",
    "tidal_mill": "coastal tidal mill with waterwheel at ocean's edge",
    "dock": "wooden dock with mooring posts and rope, coastal pier",
    "waystation": "waystation rest stop with crates and lantern",
    "road_segment": "cobblestone road section with worn wheel ruts",
    "road_dirt_ew": "dirt road running east-west, rutted earth path",
    "road_paved_ew": "paved stone road running east-west, flat cobblestones",
    "road_intersection": "crossroads intersection with worn stone",
    "residence": "cozy stone cottage with thatched roof and chimney smoke",
    "store": "merchant shop front with awning and displayed wares",
    "bank_building": "stone bank building with heavy wooden door and vault sign",
    "apothecary": "apothecary shop with hanging herbs and medicine bottles",
    "field_stockade": "wooden stockade fence with watchtower",
    "drill_rig": "oil drill rig with wooden derrick and pipes",
    "shipyard": "shipyard with wooden hull frame under construction, maritime tools",
    "warehouse": "large warehouse building with double doors, storage barrels",
    "stone_works": "stone crushing works with millstones, lime kiln, cut blocks",
    "tool_cache": "locked tool shed with crates and hanging tools",
    "watch_hut": "small wooden watch hut with lantern and lookout post",
}

MATERIAL_PROMPTS: dict[str, str] = {
    # Energy & basics
    "coal": "black coal chunk with glinting facets",
    "charcoal": "charcoal chunks, black and ashy",
    "electricity": "lightning bolt in glass orb, crackling energy",
    "dissipated_energy": "faded spark dissipating into mist, spent energy",
    # Iron chain
    "iron_ore": "rough iron ore rock with metallic veins",
    "iron_ingot": "polished iron ingot bar with stamp mark",
    "steel_ingot": "gleaming steel ingot bar",
    "pig_iron": "rough pig iron ingot, dark matte",
    "cast_iron": "cast iron block with rough surface",
    # Copper & tin & lead
    "copper_ore": "copper ore chunk with green oxidation",
    "copper_ingot": "copper ingot bar with warm reddish-brown sheen",
    "copper_wire": "coiled copper wire spool",
    "tin_ore": "tin ore nodule, grey metallic",
    "tin_ingot": "tin ingot bar, silvery grey",
    "lead_ore": "lead ore chunk, dull grey",
    "lead_ingot": "heavy lead ingot bar",
    "bronze_ingot": "bronze ingot with warm golden-brown sheen",
    # Wood & construction
    "timber": "rough timber log section with bark",
    "lumber": "smooth-cut lumber plank",
    "brick": "clay brick, earthy red",
    "stone": "cut stone block, grey granite",
    "clay": "lump of wet clay, terracotta color",
    "sand": "pile of sand, pale beige",
    "limestone": "limestone rock chunk, pale grey",
    "quicklime": "quicklime powder sack, white dusty",
    "mortar": "mortar mix in wooden tub",
    "glass": "clear glass bottle or lens",
    "rope": "coiled hemp rope",
    "ladder": "wooden ladder, folded",
    "pottery": "clay pot or vessel, fired terracotta",
    # Food
    "grain": "wheat grain bundle, golden",
    "flour": "flour sack with tied top, dusty white",
    "bread": "round loaf of bread, golden-brown crust",
    "fish": "fresh fish, silver scales",
    "smoked_fish": "smoked fish on wooden rack, amber color",
    "spoiled_grain": "moldy spoiled grain pile, grey-green",
    "wild_herb": "bundled wild herbs, green leaves",
    "medicine": "medicine bottle with cork stopper and cross label",
    # Chemistry & tier-2 ores
    "sulfur_ore": "yellow sulfur crystal cluster on rock",
    "saltpeter_ore": "saltpeter ore, white crystalline nodules",
    "phosphate_ore": "phosphate rock, pale mineral",
    "raw_silica": "raw silica sand rock, glassy",
    "sulfur_ore_refined": "refined sulfur crystals, bright yellow",
    "sulfuric_acid": "glass flask of sulfuric acid, greenish liquid",
    "refined_saltpeter": "refined saltpeter crystals, white powder",
    "gunpowder": "gunpowder keg or black powder pouch",
    "phosphate_meal": "bag of phosphate meal fertilizer",
    "fused_silica": "fused silica ingot, translucent",
    "slag": "slag tailings rock, dark porous",
    # Rare / tier-3
    "platinum_ore": "silvery platinum ore chunk",
    "refined_platinum": "refined platinum bar, bright white metal",
    "oil_shale": "layered oil shale rock, dark grey-brown",
    "shale_oil": "shale oil jar, dark amber liquid",
    "rare_earth_ore": "iridescent rare earth mineral cluster",
    # Tools & parts
    "pick_axe": "iron pickaxe with wooden handle",
    "mining_pick": "heavy mining pick, reinforced head",
    "hand_saw": "hand saw with wooden handle",
    "spade": "iron spade shovel",
    "drill_bit": "steel drill bit, spiral tip",
    "pick_head": "forged pick head, iron",
    "saw_blade": "steel saw blade",
    "pump_unit": "mechanical pump unit with pipes",
    "gear_set": "interlocking gear set, brass and iron",
    # Maritime / boats (top-down game icons)
    "vessel": "top-down wooden cargo sailing ship with two masts, brown hull, tan sails, maritime trade vessel",
    "small_vessel": "top-down small wooden rowboat skiff, single mast or oars, fishing craft, compact boat",
    "boat": "top-down wooden rowboat viewed from above, simple fishing boat with oars",
    "cargo_ship": "top-down large merchant cargo ship, three masts, laden hull, trade lane vessel",
    "fishing_boat": "top-down small fishing boat with net and single sail, coastal skiff",
}

EVENT_PROMPTS: dict[str, str] = {
    "drought": "cracked dry earth under blazing sun, wilted crops",
    "blight": "wilted diseased crops with dark spots, crop blight",
    "epidemic": "red cross medical symbol with disease vapors",
    "storm": "dark storm cloud with lightning bolt",
    "mine_collapse": "cave-in rocks with broken timbers and dust",
    "seismic": "earthquake cracks in ground, shaking ground symbol",
    "flood": "blue water waves overflowing riverbank",
    "route_blocked": "broken road with barrier and warning sign",
    "boom_town": "rapidly growing town with scaffolding",
    "price_spike": "upward red arrow over gold coins",
    "price_crash": "downward arrow over broken coin",
    "discovery": "glowing magnifying glass over mineral sample",
    "brownout": "flickering lightning bolt with warning symbol",
    "trade_surplus": "scale tipping toward exports, merchant ship silhouette",
    "laborer_strike": "raised fist holding pickaxe",
    "recipe_discovery": "glowing scroll with mineral assay result",
    "price_alert": "bell with coin stack, market alert",
    "scarcity_streak": "empty market stall with warning",
    "deep_survey_find": "deep mine shaft with rare ore glow",
    "region_power_up": "power grid lightning bolt rising",
    "region_power_down": "dim power symbol failing",
}

UI_PROMPTS: dict[str, str] = {
    "claim": "land deed scroll with seal",
    "survey": "surveyor's compass on map",
    "build": "hammer and blueprint",
    "produce": "gear with output arrow",
    "ship": "sailing ship silhouette, maritime",
    "trade": "two arrows exchanging direction, trade symbol",
    "hire": "handshake symbol",
    "settings": "gear cog settings symbol",
    "finance": "coin stack with upward arrow",
    "science": "atom symbol or flask",
    "chronicle": "open book with quill pen",
    "pacts": "two hands shaking over scroll",
    "power": "electrical bolt in circle",
    "labor": "worker figure with tool",
    "territory": "land parcel map with boundary",
    "operations": "factory gear and ledger",
    "market": "market stall with scales",
    "inventory": "wooden crate with goods",
    "caravans": "wagon train or ship convoy",
    "economics": "chart line trending up",
    "tenders": "sealed bid envelope",
    "business": "shopfront with coin",
    "menu": "profile portrait frame",
    "save": "floppy scroll save symbol",
    "pause": "pause bars symbol",
    "map": "folded parchment map",
}

TERRAIN_PROMPTS: dict[str, str] = {
    "plains": "golden-green grassland, gentle rolling hills, seamless texture tile",
    "forest": "dense dark green forest canopy viewed from above, texture tile",
    "temperate_forest": "temperate forest canopy, mixed green-brown, texture tile",
    "mountain": "grey rocky mountain peak with snow, aerial texture tile",
    "hills": "rolling green hills, moderate elevation, texture tile",
    "desert": "sandy desert with dune ripples, warm gold texture tile",
    "tundra": "icy tundra, pale blue-white frozen ground, texture tile",
    "coastal": "sandy beach at ocean edge, pale sand and foam, texture tile",
    "valley": "green fertile valley floor, lush vegetation, texture tile",
    "swamp": "dark murky swamp with reeds and still water, texture tile",
    "tropical": "vibrant tropical jungle canopy, bright greens, texture tile",
    "water_shallow": "shallow coastal water, turquoise with sand patches, texture tile",
    "water_deep": "deep ocean water, dark blue waves, texture tile",
}
