"""
Per-asset prompt library for Realm.
Each entry is the descriptive part added to STYLE_BASE.
"""

BUILDING_PROMPTS: dict[str, str] = {
    "strip_mine": "open-pit mine with ore carts and wooden scaffolding, rocky excavation",
    "foundry": "iron foundry with brick smokestack, molten metal glow, anvil and bellows",
    "timber_yard": "lumber yard with stacked logs, sawmill wheel, wood shavings",
    "grain_row": "wheat field row with golden stalks, sheaves of grain",
    "gristmill": "stone watermill with turning wheel, grain sacks",
    "kiln_shed": "brick kiln shed with orange fire glow, clay pots",
    "wood_shop": "carpenter workshop with plane, saw, wood planks",
    "blast_furnace": "tall blast furnace with molten metal pour, smoke and fire",
    "chemical_works": "alchemical laboratory with glass retorts, colorful vapors",
    "forge_press": "blacksmith forge with press mechanism, glowing hot metal",
    "tool_workshop": "tool workshop with organized tools hanging on wall",
    "machine_shop": "mechanical workshop with gears and precision instruments",
    "assay_lab": "mineral assay laboratory with test tubes and scales",
    "laboratory": "scientific laboratory with chemistry apparatus, periodic table",
    "power_shed": "electricity generator shed with coils and lightning bolt",
    "tidal_mill": "coastal tidal mill with waterwheel at ocean's edge",
    "dock": "wooden dock with mooring posts and rope, coastal",
    "waystation": "waystation rest stop with crates and lantern",
    "road_segment": "cobblestone road section with worn wheel ruts",
    "road_dirt_ew": "dirt road running east-west, rutted earth path",
    "road_paved_ew": "paved stone road running east-west, flat cobblestones",
    "road_intersection": "crossroads intersection with worn stone",
    "residence": "cozy stone cottage with thatched roof and chimney smoke",
    "store": "merchant shop front with awning and displayed wares",
    "bank_building": "stone bank building with heavy wooden door and vault sign",
    "apothecary": "apothecary shop with hanging herbs and medicine bottles",
    "field_stockade": "wooden stockade fence with watchtower",
    "drill_rig": "oil drill rig with wooden derrick and pipes",
    "shipyard": "shipyard with hull frame under construction, maritime tools",
    "warehouse": "large warehouse building with double doors, storage barrels",
}

MATERIAL_PROMPTS: dict[str, str] = {
    "coal": "black coal chunk with glinting facets",
    "iron_ore": "rough iron ore rock with metallic veins",
    "iron_ingot": "polished iron ingot bar with stamp mark",
    "steel_ingot": "gleaming steel ingot bar",
    "copper_ore": "copper ore chunk with green oxidation",
    "copper_ingot": "copper ingot bar with warm reddish-brown sheen",
    "tin_ore": "tin ore nodule, grey metallic",
    "timber": "rough timber log section with bark",
    "lumber": "smooth-cut lumber plank",
    "grain": "wheat grain bundle, golden",
    "flour": "flour sack with tied top, dusty white",
    "bread": "round loaf of bread, golden-brown crust",
    "brick": "clay brick, earthy red",
    "stone": "cut stone block, grey granite",
    "clay": "lump of wet clay, terracotta color",
    "electricity": "lightning bolt in glass orb, crackling energy",
    "rope": "coiled hemp rope",
    "medicine": "medicine bottle with cork stopper and cross label",
    "vessel": "wooden sailing vessel, small boat",
    "pick_axe": "iron pickaxe with wooden handle",
    "drill_bit": "steel drill bit, spiral tip",
    "charcoal": "charcoal chunks, black and ashy",
    "glass": "clear glass bottle or lens",
    "sulfur": "yellow sulfur crystal cluster",
    "phosphate_ore": "phosphate rock, pale mineral",
    "rare_earth_ore": "iridescent rare earth mineral",
    "gold": "gold nugget or flake, brilliant yellow",
    "platinum_ore": "silvery platinum ore chunk",
    "oil_shale": "layered oil shale rock, dark grey-brown",
    "gunpowder": "gunpowder keg or black powder pouch",
    "fertilizer": "bag of granular fertilizer, soil-enriching",
    "fish": "fresh fish, silver scales",
    "wild_herb": "bundled wild herbs, green leaves",
    "pottery": "clay pot or vessel, fired terracotta",
}

EVENT_PROMPTS: dict[str, str] = {
    "drought": "cracked dry earth under blazing sun, wilted crops",
    "epidemic": "red cross medical symbol with disease vapors",
    "storm": "dark storm cloud with lightning bolt",
    "mine_collapse": "cave-in rocks with broken timbers and dust",
    "flood": "blue water waves overflowing riverbank",
    "route_blocked": "broken road with barrier and warning sign",
    "boom_town": "rapidly growing town with scaffolding",
    "price_spike": "upward red arrow over gold coins",
    "price_crash": "downward arrow over broken coin",
    "discovery": "glowing light bulb or magnifying glass over scroll",
    "brownout": "flickering lightning bolt with warning symbol",
    "trade_surplus": "scale tipping toward exports, merchant ship",
    "laborer_strike": "raised fist holding pickaxe",
}

UI_PROMPTS: dict[str, str] = {
    "claim": "land deed scroll with seal",
    "survey": "surveyor's compass on map",
    "build": "hammer and blueprint",
    "produce": "gear with output arrow",
    "ship": "sailing ship silhouette",
    "trade": "two arrows exchanging direction, trade symbol",
    "hire": "handshake symbol",
    "settings": "gear cog settings symbol",
    "finance": "coin stack with upward arrow",
    "science": "atom symbol or flask",
    "chronicle": "open book with quill pen",
    "pacts": "two hands shaking over scroll",
    "power": "electrical bolt in circle",
    "labor": "worker figure with tool",
}

TERRAIN_PROMPTS: dict[str, str] = {
    "plains": "golden-green grassland, gentle rolling hills, texture tile",
    "forest": "dense dark green forest canopy viewed from above, texture tile",
    "mountain": "grey rocky mountain peak with snow, aerial texture tile",
    "hills": "rolling green hills, moderate elevation, texture tile",
    "desert": "sandy desert with dune ripples, warm gold texture tile",
    "tundra": "icy tundra, pale blue-white frozen ground, texture tile",
    "coastal": "sandy beach at ocean edge, pale sand and foam, texture tile",
    "valley": "green fertile valley floor, lush vegetation, texture tile",
    "swamp": "dark murky swamp with reeds and still water, texture tile",
    "tropical": "vibrant tropical jungle canopy, bright greens, texture tile",
}
