class_name BazaarMaterials
extends RefCounted
## Static material lists for Bazaar UI (display grouping; engine validates trades).

const REGION_IDS: PackedStringArray = [
	"r-0-0", "r-1-0", "r-2-0", "r-0-1", "r-1-1", "r-2-1", "r-0-2", "r-1-2", "r-2-2",
]

const MATERIAL_CATEGORIES: Dictionary = {
	"Raw Materials": [
		"iron_ore",
		"coal",
		"copper_ore",
		"tin_ore",
		"lead_ore",
		"sulfur_ore",
		"phosphate_ore",
		"rare_earth_ore",
		"saltpeter_ore",
		"platinum_ore",
		"oil_shale",
		"stone",
		"clay",
		"sand",
		"raw_silica",
	],
	"Agricultural": [
		"grain",
		"flour",
		"bread",
		"fish",
		"smoked_fish",
		"wild_herb",
		"medicine",
		"spoiled_grain",
	],
	"Processed Metals": [
		"iron_ingot",
		"steel_ingot",
		"copper_ingot",
		"tin_ingot",
		"lead_ingot",
		"pig_iron",
		"cast_iron",
		"bronze_ingot",
		"refined_platinum",
		"copper_wire",
	],
	"Construction": [
		"lumber",
		"timber",
		"brick",
		"limestone",
		"mortar",
		"rope",
		"glass",
		"fused_silica",
		"quicklime",
		"phosphate_meal",
	],
	"Tools & Equipment": [
		"pick_axe",
		"hand_saw",
		"mining_pick",
		"spade",
		"drill_bit",
		"pick_head",
		"saw_blade",
		"pump_unit",
		"gear_set",
		"ladder",
		"vessel",
		"small_vessel",
	],
	"Energy": ["electricity", "charcoal", "shale_oil"],
	"Chemicals": [
		"sulfuric_acid",
		"gunpowder",
		"sulfur_ore_refined",
		"refined_saltpeter",
		"pottery",
	],
	"Rare & Precious": ["platinum_ore", "refined_platinum", "rare_earth_ore"],
	"Other": ["slag", "dissipated_energy"],
}

const ALL_MATERIALS: PackedStringArray = [
	"bread",
		"brick",
		"bronze_ingot",
		"cast_iron",
		"charcoal",
		"clay",
		"coal",
		"copper_ingot",
		"copper_ore",
		"copper_wire",
		"drill_bit",
		"dissipated_energy",
		"electricity",
		"fish",
		"flour",
		"fused_silica",
		"gear_set",
		"glass",
		"grain",
		"gunpowder",
		"hand_saw",
		"iron_ingot",
		"iron_ore",
		"ladder",
		"lead_ingot",
		"lead_ore",
		"limestone",
		"lumber",
		"medicine",
		"mining_pick",
		"mortar",
		"oil_shale",
		"phosphate_meal",
		"phosphate_ore",
		"pick_axe",
		"pick_head",
		"pig_iron",
		"platinum_ore",
		"pottery",
		"pump_unit",
		"quicklime",
		"rare_earth_ore",
		"raw_silica",
		"refined_platinum",
		"refined_saltpeter",
		"rope",
		"saltpeter_ore",
		"sand",
		"saw_blade",
		"shale_oil",
		"slag",
		"small_vessel",
		"smoked_fish",
		"spade",
		"spoiled_grain",
		"steel_ingot",
		"stone",
		"sulfur_ore",
		"sulfur_ore_refined",
		"sulfuric_acid",
		"timber",
		"tin_ingot",
		"tin_ore",
		"vessel",
	"wild_herb",
]

const SURVEY_MINERALS: PackedStringArray = [
	"iron_ore",
	"coal",
	"copper_ore",
	"clay",
	"tin",
	"lead",
	"sulfur",
	"phosphate",
	"silica",
	"platinum",
	"oil_shale",
	"rare_earth",
]

const EFFICIENCY_CATEGORIES: PackedStringArray = [
	"mining", "agriculture", "manufacturing", "chemical", "timber", "construction",
]
