"""Hand-authored recipe templates (Primitive 6) — Phase 1 starter set."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Final, Mapping

from realm.core.ids import MaterialId
from realm.core.time_scale import TICKS_PER_GAME_DAY, legacy_scaled

# In-game hours → ticks (1 tick = 1 in-game minute per ``time_scale``).
_TICKS_PER_GAME_HOUR: int = TICKS_PER_GAME_DAY // 24


@dataclass(frozen=True, slots=True)
class Recipe:
    recipe_id: str
    display_name: str
    inputs: dict[MaterialId, int]
    outputs: dict[MaterialId, int]
    duration_ticks: int
    labor_cents: int  # paid to system reserve at production start (wage reserve)
    requires_building_id: str  # plot must have this building_id (effective) to run recipe
    # Optional extraction gates: surveyed plot subsurface field must be >= min (0..1 rolls).
    requires_subsurface: tuple[tuple[str, float], ...] = ()
    # If set, scales that output material quantity by subsurface grade (field must match a gate).
    scaled_output: tuple[str, MaterialId] | None = None
    # Tier 0: party must hold this tool (not consumed). No workshop check when set.
    requires_tool: MaterialId | None = None
    # When True, the recipe must appear in ``world.party_recipe_books[party]`` before it can run.
    # Tier-2/Tier-3 industrial recipes unlock through the assay & deep-survey systems.
    requires_discovery: bool = False
    # Optional substitutes: primary material id → [(substitute_id, ratio), ...]
    input_substitutes: dict[str, list[tuple[str, float]]] = field(default_factory=dict)


RECIPES: Final[Mapping[str, Recipe]] = {
    "sawmill": Recipe(
        recipe_id="sawmill",
        display_name="Sawmill (timber → lumber)",
        inputs={MaterialId("timber"): 2, MaterialId("electricity"): 1},
        outputs={MaterialId("lumber"): 1},
        duration_ticks=legacy_scaled(2),
        labor_cents=5_00,
        requires_building_id="wood_shop",
    ),
    "smelt_iron": Recipe(
        recipe_id="smelt_iron",
        display_name="Smelt iron",
        inputs={
            MaterialId("iron_ore"): 1,
            MaterialId("coal"): 1,
            MaterialId("electricity"): 1,
        },
        outputs={MaterialId("iron_ingot"): 1},
        duration_ticks=legacy_scaled(3),
        labor_cents=8_00,
        requires_building_id="foundry",
        input_substitutes={"coal": [("charcoal", 1.5)]},
    ),
    "smelt_copper": Recipe(
        recipe_id="smelt_copper",
        display_name="Smelt copper",
        inputs={
            MaterialId("copper_ore"): 1,
            MaterialId("coal"): 1,
            MaterialId("electricity"): 1,
        },
        outputs={MaterialId("copper_ingot"): 1},
        duration_ticks=legacy_scaled(3),
        labor_cents=8_00,
        requires_building_id="foundry",
    ),
    "coal_generator": Recipe(
        recipe_id="coal_generator",
        display_name="Generator (coal → electricity)",
        inputs={MaterialId("coal"): 1},
        outputs={MaterialId("electricity"): 2},
        duration_ticks=legacy_scaled(2),
        labor_cents=2_00,
        requires_building_id="power_shed",
        input_substitutes={
            "coal": [("charcoal", 1.2), ("shale_oil", 0.8)],
        },
    ),
    # Sprint 3 — Phase D.4: coastal renewable power. Half the rate of a
    # coal generator (1 unit / 720 ticks vs 2 units / 120 ticks) but no fuel.
    "tidal_power": Recipe(
        recipe_id="tidal_power",
        display_name="Tidal power (no fuel — coastal renewable)",
        inputs={},
        outputs={MaterialId("electricity"): 1},
        duration_ticks=720,
        labor_cents=1_00,
        requires_building_id="tidal_mill",
    ),
    "kiln_brick": Recipe(
        recipe_id="kiln_brick",
        display_name="Kiln (clay → brick)",
        inputs={
            MaterialId("clay"): 2,
            MaterialId("coal"): 1,
            MaterialId("electricity"): 1,
        },
        outputs={MaterialId("brick"): 2},
        duration_ticks=legacy_scaled(4),
        labor_cents=6_00,
        requires_building_id="kiln_shed",
    ),
    "mine_stone": Recipe(
        recipe_id="mine_stone",
        display_name="Strip & crush (timber + power → stone)",
        inputs={MaterialId("timber"): 1, MaterialId("electricity"): 1},
        outputs={MaterialId("stone"): 2},
        duration_ticks=legacy_scaled(2),
        labor_cents=3_00,
        requires_building_id="stone_works",
    ),
    "wash_sand": Recipe(
        recipe_id="wash_sand",
        display_name="Wash & grade (stone + power → sand)",
        inputs={MaterialId("stone"): 2, MaterialId("electricity"): 1},
        outputs={MaterialId("sand"): 3},
        duration_ticks=legacy_scaled(2),
        labor_cents=3_00,
        requires_building_id="stone_works",
    ),
    "crush_limestone": Recipe(
        recipe_id="crush_limestone",
        display_name="Crush & calcine prep (stone → limestone + slag)",
        inputs={MaterialId("stone"): 3, MaterialId("electricity"): 1},
        outputs={MaterialId("limestone"): 2, MaterialId("slag"): 2},
        duration_ticks=legacy_scaled(3),
        labor_cents=4_00,
        requires_building_id="stone_works",
    ),
    "lime_burn": Recipe(
        recipe_id="lime_burn",
        display_name="Lime kiln (limestone + coal + power → quicklime + slag)",
        inputs={
            MaterialId("limestone"): 2,
            MaterialId("coal"): 1,
            MaterialId("electricity"): 1,
        },
        outputs={MaterialId("quicklime"): 1, MaterialId("slag"): 3},
        duration_ticks=legacy_scaled(4),
        labor_cents=6_00,
        requires_building_id="stone_works",
    ),
    "mortar_mix": Recipe(
        recipe_id="mortar_mix",
        display_name="Mortar (quicklime + sand + power → mortar + slag)",
        inputs={
            MaterialId("quicklime"): 1,
            MaterialId("sand"): 2,
            MaterialId("electricity"): 1,
        },
        outputs={MaterialId("mortar"): 2, MaterialId("slag"): 2},
        duration_ticks=legacy_scaled(2),
        labor_cents=3_00,
        requires_building_id="stone_works",
    ),
    "glass_blow": Recipe(
        recipe_id="glass_blow",
        display_name="Glass furnace (sand + coal + power → glass + slag)",
        inputs={
            MaterialId("sand"): 2,
            MaterialId("coal"): 1,
            MaterialId("electricity"): 1,
        },
        outputs={MaterialId("glass"): 1, MaterialId("slag"): 3},
        duration_ticks=legacy_scaled(4),
        labor_cents=7_00,
        requires_building_id="stone_works",
    ),
    "steel_alloy": Recipe(
        recipe_id="steel_alloy",
        display_name="Steel (iron + coal + power → steel + slag)",
        inputs={
            MaterialId("iron_ingot"): 1,
            MaterialId("coal"): 1,
            MaterialId("electricity"): 1,
        },
        outputs={MaterialId("steel_ingot"): 1, MaterialId("slag"): 2},
        duration_ticks=legacy_scaled(4),
        labor_cents=10_00,
        requires_building_id="foundry",
    ),
    "wire_draw": Recipe(
        recipe_id="wire_draw",
        display_name="Wire draw (copper ingot + power → wire)",
        inputs={MaterialId("copper_ingot"): 1, MaterialId("electricity"): 1},
        outputs={MaterialId("copper_wire"): 2},
        duration_ticks=legacy_scaled(2),
        labor_cents=4_00,
        requires_building_id="foundry",
    ),
    "charcoal_burn": Recipe(
        recipe_id="charcoal_burn",
        display_name="Charcoal retort (timber + power → charcoal + slag)",
        inputs={MaterialId("timber"): 2, MaterialId("electricity"): 1},
        outputs={MaterialId("charcoal"): 2, MaterialId("slag"): 1},
        duration_ticks=legacy_scaled(5),
        labor_cents=2_00,
        requires_building_id="wood_shop",
    ),
    "pottery_kiln": Recipe(
        recipe_id="pottery_kiln",
        display_name="Pottery (clay + coal + power → pottery + slag)",
        inputs={
            MaterialId("clay"): 2,
            MaterialId("coal"): 1,
            MaterialId("electricity"): 1,
        },
        outputs={MaterialId("pottery"): 2, MaterialId("slag"): 2},
        duration_ticks=legacy_scaled(4),
        labor_cents=5_00,
        requires_building_id="kiln_shed",
    ),
    "mill_flour": Recipe(
        recipe_id="mill_flour",
        display_name="Mill (grain + power → flour)",
        inputs={MaterialId("grain"): 2, MaterialId("electricity"): 2},
        outputs={MaterialId("flour"): 4},
        duration_ticks=legacy_scaled(2),
        labor_cents=3_00,
        requires_building_id="gristmill",
    ),
    "bake_bread": Recipe(
        recipe_id="bake_bread",
        display_name="Bake (flour + power → bread)",
        inputs={MaterialId("flour"): 2, MaterialId("electricity"): 2},
        outputs={MaterialId("bread"): 4},
        duration_ticks=legacy_scaled(3),
        labor_cents=4_00,
        requires_building_id="gristmill",
        input_substitutes={"flour": [("grain", 2.0)]},
    ),
    "twist_rope": Recipe(
        recipe_id="twist_rope",
        display_name="Twist cordage (timber + power → rope)",
        inputs={MaterialId("timber"): 1, MaterialId("electricity"): 1},
        outputs={MaterialId("rope"): 3},
        duration_ticks=legacy_scaled(2),
        labor_cents=2_00,
        requires_building_id="wood_shop",
    ),
    "build_ladder": Recipe(
        recipe_id="build_ladder",
        display_name="Assemble ladder (lumber + rope + power)",
        inputs={
            MaterialId("lumber"): 2,
            MaterialId("rope"): 2,
            MaterialId("electricity"): 1,
        },
        outputs={MaterialId("ladder"): 1},
        duration_ticks=legacy_scaled(3),
        labor_cents=6_00,
        requires_building_id="wood_shop",
        input_substitutes={"lumber": [("timber", 2.0)]},
    ),
    # Extraction / primary sector — subsurface grades matter once surveyed (Genesis + Frontier).
    "mine_iron_ore": Recipe(
        recipe_id="mine_iron_ore",
        display_name="Mine iron ore (power + labor)",
        inputs={MaterialId("electricity"): 2},
        outputs={MaterialId("iron_ore"): 2},
        duration_ticks=legacy_scaled(3),
        labor_cents=2_50,
        requires_building_id="strip_mine",
        requires_subsurface=(("iron_ore_grade", 0.3),),
        scaled_output=("iron_ore_grade", MaterialId("iron_ore")),
    ),
    "mine_copper_ore": Recipe(
        recipe_id="mine_copper_ore",
        display_name="Mine copper ore (power + labor)",
        inputs={MaterialId("electricity"): 2},
        outputs={MaterialId("copper_ore"): 2},
        duration_ticks=legacy_scaled(3),
        labor_cents=2_50,
        requires_building_id="strip_mine",
        requires_subsurface=(("copper_ore_grade", 0.3),),
        scaled_output=("copper_ore_grade", MaterialId("copper_ore")),
    ),
    "mine_coal": Recipe(
        recipe_id="mine_coal",
        display_name="Mine coal (power + labor)",
        inputs={MaterialId("electricity"): 2},
        outputs={MaterialId("coal"): 2},
        duration_ticks=legacy_scaled(3),
        labor_cents=2_00,
        requires_building_id="strip_mine",
        requires_subsurface=(("coal_grade", 0.3),),
        scaled_output=("coal_grade", MaterialId("coal")),
    ),
    "dig_clay": Recipe(
        recipe_id="dig_clay",
        display_name="Dig clay (power + labor)",
        inputs={MaterialId("electricity"): 1},
        outputs={MaterialId("clay"): 2},
        duration_ticks=legacy_scaled(2),
        labor_cents=2_00,
        requires_building_id="strip_mine",
        requires_subsurface=(("clay_grade", 0.3),),
        scaled_output=("clay_grade", MaterialId("clay")),
    ),
    "chop_timber": Recipe(
        recipe_id="chop_timber",
        display_name="Chop timber (labor + power)",
        inputs={MaterialId("electricity"): 1},
        outputs={MaterialId("timber"): 2},
        duration_ticks=legacy_scaled(2),
        labor_cents=1_50,
        requires_building_id="timber_yard",
    ),
    "grow_grain": Recipe(
        recipe_id="grow_grain",
        display_name="Grow grain (irrigated row — power + labor)",
        inputs={MaterialId("electricity"): 2},
        outputs={MaterialId("grain"): 3},
        duration_ticks=legacy_scaled(5),
        labor_cents=2_50,
        requires_building_id="grain_row",
    ),
    "hand_chop": Recipe(
        recipe_id="hand_chop",
        display_name="Hand chop (pick axe — no building)",
        inputs={},
        outputs={MaterialId("timber"): 1},
        duration_ticks=4 * _TICKS_PER_GAME_HOUR,
        labor_cents=2_50,
        requires_building_id="",
        requires_tool=MaterialId("pick_axe"),
    ),
    "fishing": Recipe(
        recipe_id="fishing",
        display_name="Fishing (coastal — no building needed)",
        inputs={},
        # Sprint 3 — Phase D.1: real fish material (was grain proxy in Sprint 1).
        outputs={MaterialId("fish"): 2},
        duration_ticks=2 * _TICKS_PER_GAME_HOUR,
        labor_cents=80,
        requires_building_id="",
        # ``hand_saw`` doubles as fishing tackle in Sprint 1; revisit once a dedicated tool exists.
        requires_tool=MaterialId("hand_saw"),
    ),
    "smoke_fish": Recipe(
        recipe_id="smoke_fish",
        display_name="Smoke fish (wood_shop)",
        inputs={MaterialId("fish"): 3, MaterialId("timber"): 1},
        outputs={MaterialId("smoked_fish"): 4},
        duration_ticks=3 * _TICKS_PER_GAME_HOUR,
        labor_cents=200,
        requires_building_id="wood_shop",
    ),
    "hand_mine_coal": Recipe(
        recipe_id="hand_mine_coal",
        display_name="Hand mine coal (mining pick — no building)",
        inputs={},
        outputs={MaterialId("coal"): 1},
        duration_ticks=6 * _TICKS_PER_GAME_HOUR,
        labor_cents=3_00,
        requires_building_id="",
        requires_subsurface=(("coal_grade", 0.3),),
        scaled_output=("coal_grade", MaterialId("coal")),
        requires_tool=MaterialId("mining_pick"),
    ),
    "hand_mine_ore": Recipe(
        recipe_id="hand_mine_ore",
        display_name="Hand mine iron ore (mining pick — no building)",
        inputs={},
        outputs={MaterialId("iron_ore"): 1},
        duration_ticks=8 * _TICKS_PER_GAME_HOUR,
        labor_cents=3_50,
        requires_building_id="",
        requires_subsurface=(("iron_ore_grade", 0.3),),
        scaled_output=("iron_ore_grade", MaterialId("iron_ore")),
        requires_tool=MaterialId("mining_pick"),
    ),
    "hand_dig_clay": Recipe(
        recipe_id="hand_dig_clay",
        display_name="Hand dig clay (spade — no building)",
        inputs={},
        outputs={MaterialId("clay"): 1},
        duration_ticks=3 * _TICKS_PER_GAME_HOUR,
        labor_cents=2_00,
        requires_building_id="",
        requires_subsurface=(("clay_grade", 0.3),),
        scaled_output=("clay_grade", MaterialId("clay")),
        requires_tool=MaterialId("spade"),
    ),
    # ─────────────── Tier-2 extraction recipes (locked behind assay discovery) ───────────────
    "mine_sulfur_ore": Recipe(
        recipe_id="mine_sulfur_ore",
        display_name="Mine sulfur ore (strip mine — power + labor)",
        inputs={MaterialId("electricity"): 2},
        outputs={MaterialId("sulfur_ore"): 1},
        duration_ticks=4 * _TICKS_PER_GAME_HOUR,
        labor_cents=7_00,
        requires_building_id="strip_mine",
        requires_subsurface=(("sulfur_grade", 0.3),),
        scaled_output=("sulfur_grade", MaterialId("sulfur_ore")),
        requires_discovery=True,
    ),
    "mine_saltpeter": Recipe(
        recipe_id="mine_saltpeter",
        display_name="Mine saltpeter (strip mine — power + labor)",
        inputs={MaterialId("electricity"): 2},
        outputs={MaterialId("saltpeter_ore"): 1},
        duration_ticks=4 * _TICKS_PER_GAME_HOUR,
        labor_cents=7_00,
        requires_building_id="strip_mine",
        requires_subsurface=(("saltpeter_grade", 0.3),),
        scaled_output=("saltpeter_grade", MaterialId("saltpeter_ore")),
        requires_discovery=True,
    ),
    "mine_tin_ore": Recipe(
        recipe_id="mine_tin_ore",
        display_name="Mine tin ore (strip mine — power + labor)",
        inputs={MaterialId("electricity"): 2},
        outputs={MaterialId("tin_ore"): 1},
        duration_ticks=4 * _TICKS_PER_GAME_HOUR,
        labor_cents=7_00,
        requires_building_id="strip_mine",
        requires_subsurface=(("tin_grade", 0.3),),
        scaled_output=("tin_grade", MaterialId("tin_ore")),
        requires_discovery=True,
    ),
    "mine_lead_ore": Recipe(
        recipe_id="mine_lead_ore",
        display_name="Mine lead ore (strip mine — power + labor)",
        inputs={MaterialId("electricity"): 2},
        outputs={MaterialId("lead_ore"): 1},
        duration_ticks=5 * _TICKS_PER_GAME_HOUR,
        labor_cents=8_00,
        requires_building_id="strip_mine",
        requires_subsurface=(("lead_grade", 0.3),),
        scaled_output=("lead_grade", MaterialId("lead_ore")),
        requires_discovery=True,
    ),
    "mine_phosphate": Recipe(
        recipe_id="mine_phosphate",
        display_name="Mine phosphate ore (strip mine — power + labor)",
        inputs={MaterialId("electricity"): 1},
        outputs={MaterialId("phosphate_ore"): 2},
        duration_ticks=3 * _TICKS_PER_GAME_HOUR,
        labor_cents=5_00,
        requires_building_id="strip_mine",
        requires_subsurface=(("phosphate_grade", 0.3),),
        scaled_output=("phosphate_grade", MaterialId("phosphate_ore")),
        requires_discovery=True,
    ),
    "mine_raw_silica": Recipe(
        recipe_id="mine_raw_silica",
        display_name="Mine raw silica (stone works — power + labor)",
        inputs={MaterialId("stone"): 2, MaterialId("electricity"): 1},
        outputs={MaterialId("raw_silica"): 3},
        duration_ticks=3 * _TICKS_PER_GAME_HOUR,
        labor_cents=4_00,
        requires_building_id="stone_works",
        requires_subsurface=(("silica_grade", 0.2),),
        scaled_output=("silica_grade", MaterialId("raw_silica")),
        requires_discovery=True,
    ),
    "hand_mine_sulfur": Recipe(
        recipe_id="hand_mine_sulfur",
        display_name="Hand mine sulfur (mining pick — no building)",
        inputs={},
        outputs={MaterialId("sulfur_ore"): 1},
        duration_ticks=8 * _TICKS_PER_GAME_HOUR,
        labor_cents=3_50,
        requires_building_id="",
        requires_subsurface=(("sulfur_grade", 0.3),),
        scaled_output=("sulfur_grade", MaterialId("sulfur_ore")),
        requires_tool=MaterialId("mining_pick"),
        requires_discovery=True,
    ),
    "hand_mine_tin": Recipe(
        recipe_id="hand_mine_tin",
        display_name="Hand mine tin (mining pick — no building)",
        inputs={},
        outputs={MaterialId("tin_ore"): 1},
        duration_ticks=10 * _TICKS_PER_GAME_HOUR,
        labor_cents=4_00,
        requires_building_id="",
        requires_subsurface=(("tin_grade", 0.3),),
        scaled_output=("tin_grade", MaterialId("tin_ore")),
        requires_tool=MaterialId("mining_pick"),
        requires_discovery=True,
    ),
    # ─────────────── Tier-2 processing chains (assay-unlocked) ───────────────
    "refine_sulfur": Recipe(
        recipe_id="refine_sulfur",
        display_name="Refine sulfur (chemical works — sulfur_ore + coal + power)",
        inputs={
            MaterialId("sulfur_ore"): 2,
            MaterialId("coal"): 1,
            MaterialId("electricity"): 1,
        },
        outputs={MaterialId("sulfur_ore_refined"): 2, MaterialId("slag"): 1},
        duration_ticks=4 * _TICKS_PER_GAME_HOUR,
        labor_cents=10_00,
        requires_building_id="chemical_works",
        requires_discovery=True,
    ),
    "make_sulfuric_acid": Recipe(
        recipe_id="make_sulfuric_acid",
        display_name="Sulfuric acid (chemical works — refined sulfur + power)",
        inputs={
            MaterialId("sulfur_ore_refined"): 2,
            MaterialId("electricity"): 2,
        },
        outputs={MaterialId("sulfuric_acid"): 1},
        duration_ticks=6 * _TICKS_PER_GAME_HOUR,
        labor_cents=14_00,
        requires_building_id="chemical_works",
        requires_discovery=True,
    ),
    "refine_saltpeter": Recipe(
        recipe_id="refine_saltpeter",
        display_name="Refine saltpeter (chemical works — saltpeter ore + power)",
        inputs={
            MaterialId("saltpeter_ore"): 2,
            MaterialId("electricity"): 1,
        },
        outputs={MaterialId("refined_saltpeter"): 2},
        duration_ticks=3 * _TICKS_PER_GAME_HOUR,
        labor_cents=8_00,
        requires_building_id="chemical_works",
        requires_discovery=True,
    ),
    "make_gunpowder": Recipe(
        recipe_id="make_gunpowder",
        display_name="Gunpowder (chemical works — saltpeter + charcoal + refined sulfur)",
        inputs={
            MaterialId("refined_saltpeter"): 1,
            MaterialId("charcoal"): 2,
            MaterialId("sulfur_ore_refined"): 1,
        },
        outputs={MaterialId("gunpowder"): 4},
        duration_ticks=4 * _TICKS_PER_GAME_HOUR,
        labor_cents=14_00,
        requires_building_id="chemical_works",
        requires_discovery=True,
    ),
    "smelt_tin": Recipe(
        recipe_id="smelt_tin",
        display_name="Smelt tin (foundry — tin ore + coal + power)",
        inputs={
            MaterialId("tin_ore"): 2,
            MaterialId("coal"): 1,
            MaterialId("electricity"): 1,
        },
        outputs={MaterialId("tin_ingot"): 1},
        duration_ticks=3 * _TICKS_PER_GAME_HOUR,
        labor_cents=9_00,
        requires_building_id="foundry",
        requires_discovery=True,
    ),
    "make_bronze": Recipe(
        recipe_id="make_bronze",
        display_name="Bronze (foundry — tin ingot + copper ingot + power)",
        inputs={
            MaterialId("tin_ingot"): 1,
            MaterialId("copper_ingot"): 2,
            MaterialId("electricity"): 1,
        },
        outputs={MaterialId("bronze_ingot"): 3, MaterialId("slag"): 1},
        duration_ticks=4 * _TICKS_PER_GAME_HOUR,
        labor_cents=12_00,
        requires_building_id="foundry",
        requires_discovery=True,
    ),
    "smelt_lead": Recipe(
        recipe_id="smelt_lead",
        display_name="Smelt lead (foundry — lead ore + coal + power)",
        inputs={
            MaterialId("lead_ore"): 2,
            MaterialId("coal"): 1,
            MaterialId("electricity"): 1,
        },
        outputs={MaterialId("lead_ingot"): 1},
        duration_ticks=3 * _TICKS_PER_GAME_HOUR,
        labor_cents=9_00,
        requires_building_id="foundry",
        requires_discovery=True,
    ),
    "process_phosphate": Recipe(
        recipe_id="process_phosphate",
        display_name="Process phosphate (chemical works — phosphate ore + acid + power)",
        inputs={
            MaterialId("phosphate_ore"): 3,
            MaterialId("sulfuric_acid"): 1,
            MaterialId("electricity"): 1,
        },
        outputs={MaterialId("phosphate_meal"): 4},
        duration_ticks=5 * _TICKS_PER_GAME_HOUR,
        labor_cents=11_00,
        requires_building_id="chemical_works",
        requires_discovery=True,
    ),
    "fuse_silica": Recipe(
        recipe_id="fuse_silica",
        display_name="Fuse silica (stone works — raw silica + coal + power)",
        inputs={
            MaterialId("raw_silica"): 3,
            MaterialId("coal"): 2,
            MaterialId("electricity"): 2,
        },
        outputs={MaterialId("fused_silica"): 1, MaterialId("slag"): 2},
        duration_ticks=6 * _TICKS_PER_GAME_HOUR,
        labor_cents=12_00,
        requires_building_id="stone_works",
        requires_discovery=True,
    ),
    # ─────────── Pig iron / cast iron chain (Tier-1; known by every party) ───────────
    "smelt_pig_iron": Recipe(
        recipe_id="smelt_pig_iron",
        display_name="Pig iron (blast furnace — iron ore + coal + limestone + power)",
        inputs={
            MaterialId("iron_ore"): 3,
            MaterialId("coal"): 3,
            MaterialId("limestone"): 2,
            MaterialId("electricity"): 2,
        },
        outputs={MaterialId("pig_iron"): 2, MaterialId("slag"): 3},
        duration_ticks=5 * _TICKS_PER_GAME_HOUR,
        labor_cents=20_00,
        requires_building_id="blast_furnace",
    ),
    "cast_iron_pour": Recipe(
        recipe_id="cast_iron_pour",
        display_name="Cast iron (foundry — pig iron + coal + power)",
        inputs={
            MaterialId("pig_iron"): 2,
            MaterialId("coal"): 1,
            MaterialId("electricity"): 1,
        },
        outputs={MaterialId("cast_iron"): 3, MaterialId("slag"): 2},
        duration_ticks=4 * _TICKS_PER_GAME_HOUR,
        labor_cents=14_00,
        requires_building_id="foundry",
    ),
    # ─────────── Tool components (Tier-1; require new buildings) ───────────
    "forge_pick_head": Recipe(
        recipe_id="forge_pick_head",
        display_name="Forge pick head (forge press — steel + coal + power)",
        inputs={
            MaterialId("steel_ingot"): 1,
            MaterialId("coal"): 1,
            MaterialId("electricity"): 1,
        },
        outputs={MaterialId("pick_head"): 2},
        duration_ticks=2 * _TICKS_PER_GAME_HOUR,
        labor_cents=10_00,
        requires_building_id="forge_press",
    ),
    "forge_saw_blade": Recipe(
        recipe_id="forge_saw_blade",
        display_name="Forge saw blade (forge press — steel + copper + power)",
        inputs={
            MaterialId("steel_ingot"): 1,
            MaterialId("copper_ingot"): 1,
            MaterialId("electricity"): 1,
        },
        outputs={MaterialId("saw_blade"): 2},
        duration_ticks=3 * _TICKS_PER_GAME_HOUR,
        labor_cents=12_00,
        requires_building_id="forge_press",
    ),
    "forge_drill_bit": Recipe(
        recipe_id="forge_drill_bit",
        display_name="Forge drill bit (forge press — steel + copper wire + power)",
        inputs={
            MaterialId("steel_ingot"): 1,
            MaterialId("copper_wire"): 1,
            MaterialId("electricity"): 2,
        },
        outputs={MaterialId("drill_bit"): 2},
        duration_ticks=4 * _TICKS_PER_GAME_HOUR,
        labor_cents=18_00,
        requires_building_id="forge_press",
    ),
    "make_pump_unit": Recipe(
        recipe_id="make_pump_unit",
        display_name="Pump unit (machine shop — cast iron + copper wire + power)",
        inputs={
            MaterialId("cast_iron"): 2,
            MaterialId("copper_wire"): 2,
            MaterialId("electricity"): 2,
        },
        outputs={MaterialId("pump_unit"): 1},
        duration_ticks=5 * _TICKS_PER_GAME_HOUR,
        labor_cents=22_00,
        requires_building_id="machine_shop",
    ),
    "make_gear_set": Recipe(
        recipe_id="make_gear_set",
        display_name="Gear set (machine shop — cast iron + power)",
        inputs={
            MaterialId("cast_iron"): 3,
            MaterialId("electricity"): 1,
        },
        outputs={MaterialId("gear_set"): 2},
        duration_ticks=3 * _TICKS_PER_GAME_HOUR,
        labor_cents=14_00,
        requires_building_id="machine_shop",
    ),
    # ─────────── Assembled tools (Tier-1; tool_workshop) ───────────
    "assemble_mining_pick": Recipe(
        recipe_id="assemble_mining_pick",
        display_name="Assemble mining pick (tool workshop — pick head + timber + power)",
        inputs={
            MaterialId("pick_head"): 1,
            MaterialId("timber"): 1,
            MaterialId("electricity"): 1,
        },
        outputs={MaterialId("mining_pick"): 1},
        duration_ticks=2 * _TICKS_PER_GAME_HOUR,
        labor_cents=6_00,
        requires_building_id="tool_workshop",
    ),
    "assemble_hand_saw": Recipe(
        recipe_id="assemble_hand_saw",
        display_name="Assemble hand saw (tool workshop — saw blade + timber + power)",
        inputs={
            MaterialId("saw_blade"): 1,
            MaterialId("timber"): 1,
            MaterialId("electricity"): 1,
        },
        outputs={MaterialId("hand_saw"): 1},
        duration_ticks=2 * _TICKS_PER_GAME_HOUR,
        labor_cents=5_00,
        requires_building_id="tool_workshop",
    ),
    "assemble_pick_axe": Recipe(
        recipe_id="assemble_pick_axe",
        display_name="Assemble pick axe (tool workshop — pick head + timber)",
        inputs={
            MaterialId("pick_head"): 1,
            MaterialId("timber"): 1,
        },
        outputs={MaterialId("pick_axe"): 2},
        duration_ticks=1 * _TICKS_PER_GAME_HOUR,
        labor_cents=4_00,
        requires_building_id="tool_workshop",
    ),
    # ─────────────── Tier-3 extraction & refining (deep_survey + assay required) ───────────────
    "mine_platinum": Recipe(
        recipe_id="mine_platinum",
        display_name="Mine platinum ore (drill rig — power + labor)",
        inputs={MaterialId("electricity"): 4},
        outputs={MaterialId("platinum_ore"): 1},
        duration_ticks=12 * _TICKS_PER_GAME_HOUR,
        labor_cents=30_00,
        requires_building_id="drill_rig",
        requires_subsurface=(("platinum_grade", 0.1),),
        scaled_output=("platinum_grade", MaterialId("platinum_ore")),
        requires_discovery=True,
    ),
    "mine_oil_shale": Recipe(
        recipe_id="mine_oil_shale",
        display_name="Mine oil shale (drill rig — power + labor)",
        inputs={MaterialId("electricity"): 3},
        outputs={MaterialId("oil_shale"): 2},
        duration_ticks=8 * _TICKS_PER_GAME_HOUR,
        labor_cents=22_00,
        requires_building_id="drill_rig",
        requires_subsurface=(("oil_shale_grade", 0.1),),
        scaled_output=("oil_shale_grade", MaterialId("oil_shale")),
        requires_discovery=True,
    ),
    "mine_rare_earth": Recipe(
        recipe_id="mine_rare_earth",
        display_name="Mine rare earth ore (drill rig — power + labor)",
        inputs={MaterialId("electricity"): 4},
        outputs={MaterialId("rare_earth_ore"): 1},
        duration_ticks=14 * _TICKS_PER_GAME_HOUR,
        labor_cents=34_00,
        requires_building_id="drill_rig",
        requires_subsurface=(("rare_earth_grade", 0.1),),
        scaled_output=("rare_earth_grade", MaterialId("rare_earth_ore")),
        requires_discovery=True,
    ),
    "refine_platinum": Recipe(
        recipe_id="refine_platinum",
        display_name="Refine platinum (foundry — platinum ore + coal + power)",
        inputs={
            MaterialId("platinum_ore"): 2,
            MaterialId("coal"): 2,
            MaterialId("electricity"): 2,
        },
        outputs={MaterialId("refined_platinum"): 1, MaterialId("slag"): 3},
        duration_ticks=8 * _TICKS_PER_GAME_HOUR,
        labor_cents=28_00,
        requires_building_id="foundry",
        requires_discovery=True,
    ),
    "process_shale": Recipe(
        recipe_id="process_shale",
        display_name="Process oil shale (chemical works — oil shale + power)",
        inputs={
            MaterialId("oil_shale"): 3,
            MaterialId("electricity"): 2,
        },
        outputs={MaterialId("shale_oil"): 1, MaterialId("slag"): 4},
        duration_ticks=6 * _TICKS_PER_GAME_HOUR,
        labor_cents=18_00,
        requires_building_id="chemical_works",
        requires_discovery=True,
    ),
    # Phase 9A — Shipyard builds the durable cargo vessel that gates inter-island
    # shipping. Big bill of materials so a shipyard is a real investment, not a
    # button to spam: 8 lumber + 6 timber + 4 iron + 2 rope + electricity in,
    # 1 vessel out (4,800 kg durable asset).
    "build_cargo_vessel": Recipe(
        recipe_id="build_cargo_vessel",
        display_name="Build cargo vessel (shipyard — lumber + timber + iron + rope + power)",
        inputs={
            MaterialId("lumber"): 8,
            MaterialId("timber"): 6,
            MaterialId("iron_ingot"): 4,
            MaterialId("rope"): 2,
            MaterialId("electricity"): 3,
        },
        outputs={MaterialId("vessel"): 1},
        duration_ticks=12 * _TICKS_PER_GAME_HOUR,
        labor_cents=40_00,
        requires_building_id="shipyard",
    ),
    # Phase 8C — epidemic supply chain.
    "gather_herbs": Recipe(
        recipe_id="gather_herbs",
        display_name="Gather wild herbs (forest — no building)",
        inputs={},
        outputs={MaterialId("wild_herb"): 2},
        duration_ticks=3 * _TICKS_PER_GAME_HOUR,
        labor_cents=1_50,
        requires_building_id="",
        requires_tool=MaterialId("spade"),
    ),
    "make_medicine": Recipe(
        recipe_id="make_medicine",
        display_name="Make medicine (apothecary — herbs + coal + power)",
        inputs={
            MaterialId("wild_herb"): 3,
            MaterialId("coal"): 1,
            MaterialId("electricity"): 1,
        },
        outputs={MaterialId("medicine"): 2},
        duration_ticks=4 * _TICKS_PER_GAME_HOUR,
        labor_cents=4_00,
        requires_building_id="apothecary",
    ),
    "soil_remediation": Recipe(
        recipe_id="soil_remediation",
        display_name="Soil remediation (phosphate meal)",
        inputs={MaterialId("phosphate_meal"): 2},
        outputs={},
        duration_ticks=6 * _TICKS_PER_GAME_HOUR,
        labor_cents=2_00,
        requires_building_id="",
        requires_tool=MaterialId("spade"),
    ),
}


def recipe_public_list() -> list[dict]:
    out: list[dict] = []
    for r in RECIPES.values():
        row: dict = {
            "id": r.recipe_id,
            "display_name": r.display_name,
            "inputs": {str(k): v for k, v in r.inputs.items()},
            "outputs": {str(k): v for k, v in r.outputs.items()},
            "duration_ticks": r.duration_ticks,
            "labor_cents": r.labor_cents,
            "requires_building_id": r.requires_building_id,
        }
        if r.requires_subsurface:
            row["requires_subsurface"] = [{"field": f, "min": m} for f, m in r.requires_subsurface]
        if r.scaled_output is not None:
            fld, mid = r.scaled_output
            row["scaled_output"] = {"field": fld, "material": str(mid)}
        if r.requires_tool is not None:
            row["requires_tool"] = str(r.requires_tool)
        if r.requires_discovery:
            row["requires_discovery"] = True
        if r.input_substitutes:
            row["input_substitutes"] = {
                k: [[sub_id, ratio] for sub_id, ratio in pairs]
                for k, pairs in r.input_substitutes.items()
            }
        out.append(row)
    return out
